//################################################################################
// build_info.h
//--------------------------------------------------------------------------------

#pragma once

#include <string>

//_ Auto-generated by bump_rev.py at build time - do not edit by hand
inline const std::string DateAndTime = "2026-07-23 11:47";