//################################################################################
// index.ts
//--------------------------------------------------------------------------------
// default        Worker entrypoint; routes /ws upgrades to the right ShardObject
// ShardObject    re-exported so wrangler can bind SHARDS to this class
//--------------------------------------------------------------------------------
// Thin routing layer - all protocol logic (history/report/broadcast, SQLite
// last-10 buffer) lives in shard-object.ts. One DO instance per shard key,
// named directly off the client's ShardIdentity::ToKey().
// Client connects to:
//   wss://<this-worker>.workers.dev/ws?shard=map1062-a1b2c3d4e5f6a7b8
//--------------------------------------------------------------------------------

import { ShardObject } from "./shard-object";
import { LIVE_EVENT_MAP_IDS } from "./live_event_maps.generated";

export { ShardObject };

//_ Loose bound on shard key length; real keys are shorter (see shard_id.cpp)
const MAX_SHARD_KEY_LENGTH = 256;

//_ Matches ShardIdentity::ToKey()'s "map<mapId>-<hash>" format (shard_id.cpp).
const SHARD_KEY_PATTERN = /^map(\d+)-[0-9a-f]{16}$/;

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// fetch
//--------------------------------------------------------------------------------
// Validates the /ws upgrade and shard key, then routes to the ShardObject for
// that key via idFromName - the same key always resolves to the same instance.
// A shard key for a map outside LIVE_EVENT_MAP_IDS is rejected before that call,
// so no Durable Object gets created for a map with no live events to report -
// the authoritative gate, independent of what any client build chooses to send
// (see live_events_ui.cpp for the client-side counterpart). LIVE_EVENT_MAP_IDS
// itself is generated by scripts/sync_live_event_maps.py from the same roster
// the client compiles in, wired into `wrangler deploy`/`dev` via wrangler.toml's
// [build] command - see that file.
//--------------------------------------------------------------------------------
export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname !== "/ws") {
      return new Response("Not found", { status: 404 });
    }

    if (request.headers.get("Upgrade") !== "websocket") {
      return new Response("Expected WebSocket upgrade", { status: 426 });
    }

    const shardKey = url.searchParams.get("shard");
    if (!shardKey || shardKey.length === 0 || shardKey.length > MAX_SHARD_KEY_LENGTH) {
      return new Response("Missing or invalid 'shard' query parameter", { status: 400 });
    }

    const match = shardKey.match(SHARD_KEY_PATTERN);
    if (!match || !LIVE_EVENT_MAP_IDS.has(Number(match[1]))) {
      return new Response("No live events on this map", { status: 403 });
    }

    const id = env.SHARDS.idFromName(shardKey);
    const stub = env.SHARDS.get(id);

    return stub.fetch(request);
  },
} satisfies ExportedHandler<Env>;