//################################################################################
// bundled_icons.h
//--------------------------------------------------------------------------------
// DefaultIconEntry   one bundled texture: filename, raw PNG bytes, byte length
// g_BundledIcons/g_BundledIconsCount
//                     the full bundled set, defined in bundled_icons.generated.cpp
//--------------------------------------------------------------------------------
// Declares the table maprender.cpp's FindDefaultIcon searches when a filename
// isn't found under <addon dir>/textures (see GetOrRequestEventIcon). The table
// itself is generated at build time by tools/generate_bundled_icons.py from every
// PNG in resources/textures/ - see that script and
// src/generated/bundled_icons.generated.cpp (gitignored, regenerated by CMake on
// every build) for how the data gets here. This header only declares the shape
// both sides agree on.
//--------------------------------------------------------------------------------

#pragma once

#include <cstddef>
#include <cstdint>

//********************************************************************************
// DefaultIconEntry
//--------------------------------------------------------------------------------
// name    bundled filename, matched against disk/user references
// data    raw PNG bytes
// size    byte length of `data`
//--------------------------------------------------------------------------------
struct DefaultIconEntry
{
    const char*    name;
    const uint8_t* data;
    uint64_t       size;
};

//_ Defined in the generated .cpp; one entry per PNG in resources/textures/.
extern const DefaultIconEntry g_BundledIcons[];
extern const size_t           g_BundledIconsCount;
