#!/usr/bin/env python3
"""
sync_live_event_maps.py  —  regenerates src/live_event_maps.generated.ts from
                             ../src/events/events_live.cpp's g_LiveEvents roster.
Run from the server/ directory (wrangler invokes it that way via the [build]
command in wrangler.toml, same as bump_rev.py at the repo root).
"""

import re
from pathlib import Path

SOURCE_FILE    = Path("../src/events/events_live.cpp")
GENERATED_FILE = Path("src/live_event_maps.generated.ts")

# Matches one LiveEvent{...} entry's leading
#   "eventId", "name", continentXf, continentYf, mapId,
# fields (see LiveEvent in events_live.h for the field order) - mapId is the
# only bare integer literal in that run, so it's the one group we need.
ENTRY_PATTERN = re.compile(
    r'\{\s*"[^"]*",\s*"[^"]*",\s*[\d.]+f,\s*[\d.]+f,\s*(\d+),'
)

text = SOURCE_FILE.read_text(encoding="utf-8")
mapIds = sorted({int(m) for m in ENTRY_PATTERN.findall(text)})

if not mapIds:
    raise SystemExit(
        "[sync_live_event_maps] ERROR: no LiveEvent entries found in "
        f"{SOURCE_FILE} — check the file, or ENTRY_PATTERN if its format changed"
    )

GENERATED_FILE.write_text(
    "// Auto-generated by scripts/sync_live_event_maps.py from\n"
    "// ../src/events/events_live.cpp — do not edit by hand.\n"
    "\n"
    f"export const LIVE_EVENT_MAP_IDS = new Set([{', '.join(str(m) for m in mapIds)}]);\n",
    encoding="utf-8",
)

print(f"[sync_live_event_maps] wrote {GENERATED_FILE} with {len(mapIds)} map id(s): {mapIds}")
