#!/usr/bin/env python3
"""
Generates a host_config.h-style header from a Worker's hostname,
XOR-obfuscated with the same fixed key the matching .cpp decodes with at
runtime (see kHostXorKey in src/networking/ws_client.cpp -- keep KEY below in
sync with that one if you ever change it). Both host_config.h (the per-shard
relay) and notify_host_config.h (the region-wide notify worker, see
live-toast-handoff.md section 5) come out of this same script - one call per
file, distinguished by the optional prefix argument below.

This is NOT encryption and isn't meant to be -- it only keeps the hostname
from showing up as one plain readable string in a `strings`/hex-editor pass
over the built DLL. Anyone stepping through the DLL in a debugger, or hooking
WinHttpConnect, still sees the real host the moment the matching DecodeHost()
reconstructs it in memory to make the connection. Not a credential -- both
relays are rate-limited, validate+forward only -- so this guards against
casual scraping, not a secret.

Usage:
    python3 tools/generate_host_config.py "your-worker.your-subdomain.workers.dev" > src/networking/host_config.h
    python3 tools/generate_host_config.py "your-worker-notify.your-subdomain.workers.dev" Notify > src/networking/notify_host_config.h

Run from the repo root so the redirect lands in the right place. Pass a bare
host (no scheme, no path) -- WinHttpConnect takes host and port separately.
Both results are gitignored (src/networking/host_config.h,
src/networking/notify_host_config.h) -- never commit either.
"""
import sys

# Must match kHostXorKey in src/networking/ws_client.cpp and
# kNotifyHostXorKey in src/networking/notification_client.cpp exactly, byte
# for byte - both decode with this same key.
KEY = [0x2D, 0xC6, 0x3C, 0x78, 0x35, 0x9B, 0x3B]


def main():
    if len(sys.argv) not in (2, 3):
        print("usage: generate_host_config.py <relay-host> [prefix]", file=sys.stderr)
        print("  prefix defaults to \"\" (produces host_config.h / kHostXor).", file=sys.stderr)
        print("  e.g. \"Notify\" produces notify_host_config.h / kNotifyHostXor.", file=sys.stderr)
        sys.exit(1)

    host   = sys.argv[1]
    prefix = sys.argv[2] if len(sys.argv) == 3 else ""

    const_name = f"k{prefix}HostXor"
    len_name   = f"k{prefix}HostXorLen"
    file_stem  = f"{prefix.lower()}_host_config" if prefix else "host_config"

    encoded = [b ^ KEY[i % len(KEY)] for i, b in enumerate(host.encode("ascii"))]

    print("//################################################################################")
    print(f"// {file_stem}.h")
    print("//--------------------------------------------------------------------------------")
    print(f"// {const_name}      XOR-obfuscated relay host bytes")
    print(f"// {len_name}   byte length of {const_name}")
    print("//--------------------------------------------------------------------------------")
    print("// Generated by tools/generate_host_config.py -- do not hand-edit. This file is")
    print("// gitignored (see .gitignore) and must never be committed. See")
    print(f"// {file_stem}.example.h for the committed template/instructions this was")
    print("// produced from.")
    print("//--------------------------------------------------------------------------------")
    print()
    print("#pragma once")
    print()
    print("#include <cstddef>")
    print()
    print(f"inline constexpr unsigned char {const_name}[] = {{")
    for i in range(0, len(encoded), 12):
        chunk = encoded[i:i + 12]
        print("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    print("};")
    print(f"inline constexpr size_t {len_name} = {len(encoded)};")


if __name__ == "__main__":
    main()
