#!/usr/bin/env python3
"""
Generates src/networking/host_config.h from the relay Worker's hostname,
XOR-obfuscated with the same fixed key ws_client.cpp decodes with at runtime
(see kHostXorKey in src/networking/ws_client.cpp -- keep KEY below in sync
with that one if you ever change it).

This is NOT encryption and isn't meant to be -- it only keeps the hostname
from showing up as one plain readable string in a `strings`/hex-editor pass
over the built DLL. Anyone stepping through the DLL in a debugger, or hooking
WinHttpConnect, still sees the real host the moment DecodeHost() reconstructs
it in memory to make the connection. Not a credential -- the relay is
rate-limited, validate+forward only -- so this guards against casual
scraping, not a secret.

Usage:
    python3 tools/generate_host_config.py "your-worker.your-subdomain.workers.dev" > src/networking/host_config.h

Run from the repo root so the redirect lands in the right place. Pass a bare
host (no scheme, no path) -- WinHttpConnect takes host and port separately.
The result is gitignored (src/networking/host_config.h) -- never commit it.
"""
import sys

# Must match kHostXorKey in src/networking/ws_client.cpp exactly, byte for byte.
KEY = [0x2D, 0xC6, 0x3C, 0x78, 0x35, 0x9B, 0x3B]


def main():
    if len(sys.argv) != 2:
        print("usage: generate_host_config.py <relay-host>", file=sys.stderr)
        sys.exit(1)

    host = sys.argv[1]
    encoded = [b ^ KEY[i % len(KEY)] for i, b in enumerate(host.encode("ascii"))]

    print("//################################################################################")
    print("// host_config.h")
    print("//--------------------------------------------------------------------------------")
    print("// kHostXor      XOR-obfuscated relay host bytes")
    print("// kHostXorLen   byte length of kHostXor")
    print("//--------------------------------------------------------------------------------")
    print("// Generated by tools/generate_host_config.py -- do not hand-edit. This file is")
    print("// gitignored (see .gitignore) and must never be committed. See")
    print("// host_config.example.h for the committed template/instructions this was")
    print("// produced from.")
    print("//--------------------------------------------------------------------------------")
    print()
    print("#pragma once")
    print()
    print("#include <cstddef>")
    print()
    print("inline constexpr unsigned char kHostXor[] = {")
    for i in range(0, len(encoded), 12):
        chunk = encoded[i:i + 12]
        print("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    print("};")
    print(f"inline constexpr size_t kHostXorLen = {len(encoded)};")


if __name__ == "__main__":
    main()
