#!/usr/bin/env python3
"""
generate_version_history.py  -  regenerates
    src/generated/version_history.generated.h
from resources/localization/version_history.csv (see VersionHistoryEntry in
src/addon/version_history.h). Run from the project root; wired into
CMakeLists.txt as a custom command so it reruns automatically whenever the
CSV (or this script) changes - no manual step needed for a normal build.

Language columns are read from WE_LANGUAGE_LIST in localization_table.h, same
as generate_localization_table.py, so both CSVs stay pinned to one language
list. "version" is a third, always-English column - the short label shown in
the closed dropdown - and is never translated.

Row order is preserved exactly as authored: kVersionHistory is newest-first,
and RenderVersionHistoryWindow's dropdown defaults to row 0. Every language
column on every row must be non-empty - this is what keeps languages in sync
now that hand-editing no longer forces it structurally: an empty cell fails
the build instead of shipping a silent gap.
"""

import csv
import re
import sys
from pathlib import Path

SOURCE_HEADER  = Path("src/core/localization_table.h")
SOURCE_CSV     = Path("resources/localization/version_history.csv")
GENERATED_FILE = Path("src/generated/version_history.generated.h")

WE_LANG_RE = re.compile(r'WE_LANG\(\s*\w+\s*,\s*"([^"]+)"\s*\)')


def get_language_codes() -> list[str]:
    """Pulls language codes out of WE_LANGUAGE_LIST, in declared order."""
    text = SOURCE_HEADER.read_text(encoding="utf-8")
    m = re.search(r'#define WE_LANGUAGE_LIST(.*?)\n\n', text, re.S)
    if not m:
        raise SystemExit(
            f"[generate_version_history] ERROR: couldn't find "
            f"WE_LANGUAGE_LIST in {SOURCE_HEADER}"
        )
    codes = WE_LANG_RE.findall(m.group(1))
    if not codes:
        raise SystemExit(
            f"[generate_version_history] ERROR: WE_LANGUAGE_LIST in "
            f"{SOURCE_HEADER} matched but no WE_LANG(...) entries parsed"
        )
    return codes


def cpp_escape(text: str) -> str:
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    return "".join(out)


def emit_field_lines(text: str, indent: str) -> list[str]:
    """One field's value as one or more adjacent C++ string literals, split
    at each embedded newline so a multi-paragraph notice reads as one
    literal per visual line instead of one very long line."""
    pieces = text.split("\n")
    lines = []
    for i, piece in enumerate(pieces):
        suffix = "\\n" if i < len(pieces) - 1 else ""
        lines.append(f'{indent}"{cpp_escape(piece)}{suffix}"')
    return lines


def main() -> None:
    codes = get_language_codes()
    expected_header = ["version"] + codes

    if not SOURCE_CSV.exists():
        raise SystemExit(f"[generate_version_history] ERROR: {SOURCE_CSV} not found")

    with SOURCE_CSV.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames != expected_header:
            raise SystemExit(
                f"[generate_version_history] ERROR: {SOURCE_CSV} header is "
                f"{reader.fieldnames}, expected {expected_header} (from "
                f"WE_LANGUAGE_LIST in {SOURCE_HEADER})"
            )
        rows = list(reader)

    if not rows:
        raise SystemExit(f"[generate_version_history] ERROR: {SOURCE_CSV} has no entries")

    lines = [
        "//################################################################################",
        f"// {GENERATED_FILE.name}   (see: src/addon/version_history.h)",
        "//--------------------------------------------------------------------------------",
        f"// Auto-generated by tools/generate_version_history.py from",
        f"// {SOURCE_CSV} - do not hand-edit, and do not commit (gitignored).",
        "// Regenerated automatically as part of the normal CMake build whenever the",
        "// CSV or the generator script changes.",
        "//--------------------------------------------------------------------------------",
        "",
        "//_ Newest first, exactly as ordered in the CSV - see the file header above.",
        "static constexpr VersionHistoryEntry kVersionHistory[] = {",
        "",
    ]

    for row_no, row in enumerate(rows, start=2):  # +1 header, +1 1-indexed
        version = row["version"].strip()
        values = {code: row[code] for code in codes}

        if not version:
            raise SystemExit(
                f"[generate_version_history] ERROR: {SOURCE_CSV}:{row_no} "
                f"has no text in 'version'"
            )

        empty = [c for c in codes if not values[c].strip()]
        if empty:
            raise SystemExit(
                f"[generate_version_history] ERROR: {SOURCE_CSV}:{row_no} "
                f"'{version}' is missing text for: {empty}"
            )

        lines.append(f'    {{ "{cpp_escape(version)}",')
        for i, code in enumerate(codes):
            field_lines = emit_field_lines(values[code], "        ")
            field_lines[-1] += " }," if i == len(codes) - 1 else ","
            lines.extend(field_lines)
        lines.append("")

    lines.append("};")
    lines.append("")
    lines.append(
        "inline constexpr int kVersionHistoryCount = "
        "sizeof(kVersionHistory) / sizeof(kVersionHistory[0]);"
    )
    lines.append("")

    GENERATED_FILE.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_FILE.write_text("\n".join(lines), encoding="utf-8")

    print(
        f"[generate_version_history] wrote {GENERATED_FILE} with "
        f"{len(rows)} entries, {len(codes)} language(s)"
    )


if __name__ == "__main__":
    sys.exit(main())
