#!/usr/bin/env python3
"""
generate_bundled_icons.py  —  regenerates
    src/generated/bundled_icons.generated.cpp
from every *.png in resources/textures/, embedding each as a raw byte array (see
DefaultIconEntry in src/core/bundled_icons.h). Run from the project root; wired
into CMakeLists.txt as a custom command so it reruns automatically whenever a
texture (or this script) changes - no manual step needed for a normal build.

The runtime filename each texture is matched against (GetOrRequestEventIcon)
is just its name in resources/textures/, unchanged - renaming a PNG there
renames the bundled default; there is no separate mapping to keep in sync.
"""

import sys
from pathlib import Path

SOURCE_DIR     = Path("resources/textures")
GENERATED_FILE = Path("src/generated/bundled_icons.generated.cpp")
BYTES_PER_LINE = 16


def c_identifier(stem: str) -> str:
    """Turns a filename stem into a safe, unique C identifier."""
    safe = "".join(c if c.isalnum() else "_" for c in stem)
    if safe[:1].isdigit():
        safe = "_" + safe
    return safe


def emit_array(lines: list[str], var_name: str, data: bytes) -> None:
    lines.append(f"static const uint8_t {var_name}[] = {{")
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i:i + BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")


def main() -> None:
    pngs = sorted(SOURCE_DIR.glob("*.png"))
    if not pngs:
        raise SystemExit(
            f"[generate_bundled_icons] ERROR: no PNGs found under {SOURCE_DIR}"
        )

    lines = [
        "//################################################################################",
        "// bundled_icons.generated.cpp   (see: src/core/bundled_icons.h)",
        "//--------------------------------------------------------------------------------",
        "// Auto-generated by tools/generate_bundled_icons.py from every PNG in",
        "// resources/textures/ - do not hand-edit, and do not commit (gitignored).",
        "// Regenerated automatically as part of the normal CMake build whenever a",
        "// texture or the generator script changes.",
        "//--------------------------------------------------------------------------------",
        "",
        '#include "bundled_icons.h"',
        "",
    ]

    seen_identifiers: dict[str, Path] = {}
    entries: list[tuple[str, str, int]] = []  # (runtime filename, var name, size)

    for png in pngs:
        var_name = "g_icon_" + c_identifier(png.stem)
        if var_name in seen_identifiers:
            raise SystemExit(
                f"[generate_bundled_icons] ERROR: '{png.name}' and "
                f"'{seen_identifiers[var_name].name}' both map to the identifier "
                f"'{var_name}' - rename one of them"
            )
        seen_identifiers[var_name] = png

        data = png.read_bytes()
        lines.append(f"//_ {png.stem} icon, {len(data)} bytes.")
        emit_array(lines, var_name, data)
        lines.append("")
        entries.append((png.name, var_name, len(data)))

    lines.append("const DefaultIconEntry g_BundledIcons[] = {")
    for filename, var_name, size in entries:
        lines.append(f'    {{ "{filename}", {var_name}, {size} }},')
    lines.append("};")
    lines.append(
        "const size_t g_BundledIconsCount = "
        "sizeof(g_BundledIcons) / sizeof(g_BundledIcons[0]);"
    )
    lines.append("")

    GENERATED_FILE.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_FILE.write_text("\n".join(lines), encoding="utf-8")

    total_bytes = sum(size for _, _, size in entries)
    print(
        f"[generate_bundled_icons] wrote {GENERATED_FILE} with "
        f"{len(entries)} icon(s), {total_bytes} bytes total"
    )


if __name__ == "__main__":
    sys.exit(main())
